### ISSUE TITLE
I'm struggling to run for tests...

### ISSUE THREAD

**Issue by zacaws** [stustanet/stustapay#3]
I'm very interested on this project, had the same idea and your project seems wonderful. But i'm having dificulties on setting this up. My plan is to run on a Raspberry Pi4. I saw that on github workflows ci.yml, it is said something about ubuntu. Is this needed to run ubuntu tho? If you could tell about how to setup properly the server would be great!  Thanks in advance! o/

**Comment by TheJJ** [comment]
The project is still very much in progress, so I fear is not yet usable outside our development environment.
SSP consists of multiple quite independent components, which are all centered around the core, which basically is a PostgreSQL DB. Once it becomes somewhat usable, we can surely provide more detailed setup instructions, but right now many things are just missing and need to be implemented first :smile:

**Comment by zacaws** [comment]
I've been watching the progress you've done, and think if I can receive more provide more detailed instructions on how to put all the independent components together for running tests as the environment it is running is not a problem for me now. Best wishes! 😄
